// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 865605518;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_airqr_mobile',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<GifDecodeResult> crateApiSimpleDecodeGifFile({
    required List<int> gifData,
  });

  Future<GifDecodeResult> crateApiSimpleDecodeZipFile({
    required List<int> zipData,
  });

  Future<ChunkedEncodeResult> crateApiSimpleEncodeChunkedToZip({
    required String filename,
    required List<int> data,
    required int chunkSizeKb,
    required int fps,
    required String eccLevel,
    required int packetSize,
    required double raptorqOverhead,
    required bool compress,
  });

  Future<EncodeResult> crateApiSimpleEncodeToGif({
    required String filename,
    required List<int> data,
    required int fps,
    required String eccLevel,
    required int packetSize,
    required double raptorqOverhead,
    required bool compress,
  });

  Future<void> crateApiSimpleInitApp();

  Future<DecodeStatus> crateApiSimpleProcessChunk({required List<int> data});

  Future<void> crateApiSimpleResetDecoder();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<GifDecodeResult> crateApiSimpleDecodeGifFile({
    required List<int> gifData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(gifData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_gif_decode_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleDecodeGifFileConstMeta,
        argValues: [gifData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecodeGifFileConstMeta =>
      const TaskConstMeta(debugName: "decode_gif_file", argNames: ["gifData"]);

  @override
  Future<GifDecodeResult> crateApiSimpleDecodeZipFile({
    required List<int> zipData,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(zipData, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_gif_decode_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleDecodeZipFileConstMeta,
        argValues: [zipData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecodeZipFileConstMeta =>
      const TaskConstMeta(debugName: "decode_zip_file", argNames: ["zipData"]);

  @override
  Future<ChunkedEncodeResult> crateApiSimpleEncodeChunkedToZip({
    required String filename,
    required List<int> data,
    required int chunkSizeKb,
    required int fps,
    required String eccLevel,
    required int packetSize,
    required double raptorqOverhead,
    required bool compress,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filename, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_u_32(chunkSizeKb, serializer);
          sse_encode_u_32(fps, serializer);
          sse_encode_String(eccLevel, serializer);
          sse_encode_u_16(packetSize, serializer);
          sse_encode_f_32(raptorqOverhead, serializer);
          sse_encode_bool(compress, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chunked_encode_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleEncodeChunkedToZipConstMeta,
        argValues: [
          filename,
          data,
          chunkSizeKb,
          fps,
          eccLevel,
          packetSize,
          raptorqOverhead,
          compress,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeChunkedToZipConstMeta =>
      const TaskConstMeta(
        debugName: "encode_chunked_to_zip",
        argNames: [
          "filename",
          "data",
          "chunkSizeKb",
          "fps",
          "eccLevel",
          "packetSize",
          "raptorqOverhead",
          "compress",
        ],
      );

  @override
  Future<EncodeResult> crateApiSimpleEncodeToGif({
    required String filename,
    required List<int> data,
    required int fps,
    required String eccLevel,
    required int packetSize,
    required double raptorqOverhead,
    required bool compress,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filename, serializer);
          sse_encode_list_prim_u_8_loose(data, serializer);
          sse_encode_u_32(fps, serializer);
          sse_encode_String(eccLevel, serializer);
          sse_encode_u_16(packetSize, serializer);
          sse_encode_f_32(raptorqOverhead, serializer);
          sse_encode_bool(compress, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_encode_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleEncodeToGifConstMeta,
        argValues: [
          filename,
          data,
          fps,
          eccLevel,
          packetSize,
          raptorqOverhead,
          compress,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncodeToGifConstMeta => const TaskConstMeta(
    debugName: "encode_to_gif",
    argNames: [
      "filename",
      "data",
      "fps",
      "eccLevel",
      "packetSize",
      "raptorqOverhead",
      "compress",
    ],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<DecodeStatus> crateApiSimpleProcessChunk({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_decode_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleProcessChunkConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleProcessChunkConstMeta =>
      const TaskConstMeta(debugName: "process_chunk", argNames: ["data"]);

  @override
  Future<void> crateApiSimpleResetDecoder() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleResetDecoderConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleResetDecoderConstMeta =>
      const TaskConstMeta(debugName: "reset_decoder", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ChunkedEncodeResult dco_decode_chunked_encode_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ChunkedEncodeResult(
      success: dco_decode_bool(arr[0]),
      zipData: dco_decode_opt_list_prim_u_8_strict(arr[1]),
      chunkGifs: dco_decode_list_list_prim_u_8_strict(arr[2]),
      chunkFrameCounts: dco_decode_list_prim_u_32_strict(arr[3]),
      chunkMinFrames: dco_decode_list_prim_u_32_strict(arr[4]),
      totalChunks: dco_decode_u_32(arr[5]),
      totalFrames: dco_decode_u_32(arr[6]),
      minFrames: dco_decode_u_32(arr[7]),
      errorMsg: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  DecodeStatus dco_decode_decode_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return DecodeStatus(
      status: dco_decode_String(arr[0]),
      percent: dco_decode_f_32(arr[1]),
      receivedPackets: dco_decode_u_32(arr[2]),
      expectedPackets: dco_decode_u_32(arr[3]),
      durationMs: dco_decode_u_64(arr[4]),
      totalPackets: dco_decode_u_32(arr[5]),
      filename: dco_decode_opt_String(arr[6]),
      fileData: dco_decode_opt_list_prim_u_8_strict(arr[7]),
      errorMsg: dco_decode_opt_String(arr[8]),
      sessionId: dco_decode_opt_box_autoadd_u_32(arr[9]),
    );
  }

  @protected
  EncodeResult dco_decode_encode_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return EncodeResult(
      success: dco_decode_bool(arr[0]),
      gifData: dco_decode_opt_list_prim_u_8_strict(arr[1]),
      totalFrames: dco_decode_u_32(arr[2]),
      minFrames: dco_decode_u_32(arr[3]),
      errorMsg: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GifDecodeResult dco_decode_gif_decode_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return GifDecodeResult(
      success: dco_decode_bool(arr[0]),
      filename: dco_decode_opt_String(arr[1]),
      fileData: dco_decode_opt_list_prim_u_8_strict(arr[2]),
      framesProcessed: dco_decode_u_32(arr[3]),
      qrDetected: dco_decode_u_32(arr[4]),
      errorMsg: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  ChunkedEncodeResult sse_decode_chunked_encode_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_zipData = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_chunkGifs = sse_decode_list_list_prim_u_8_strict(deserializer);
    var var_chunkFrameCounts = sse_decode_list_prim_u_32_strict(deserializer);
    var var_chunkMinFrames = sse_decode_list_prim_u_32_strict(deserializer);
    var var_totalChunks = sse_decode_u_32(deserializer);
    var var_totalFrames = sse_decode_u_32(deserializer);
    var var_minFrames = sse_decode_u_32(deserializer);
    var var_errorMsg = sse_decode_opt_String(deserializer);
    return ChunkedEncodeResult(
      success: var_success,
      zipData: var_zipData,
      chunkGifs: var_chunkGifs,
      chunkFrameCounts: var_chunkFrameCounts,
      chunkMinFrames: var_chunkMinFrames,
      totalChunks: var_totalChunks,
      totalFrames: var_totalFrames,
      minFrames: var_minFrames,
      errorMsg: var_errorMsg,
    );
  }

  @protected
  DecodeStatus sse_decode_decode_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_String(deserializer);
    var var_percent = sse_decode_f_32(deserializer);
    var var_receivedPackets = sse_decode_u_32(deserializer);
    var var_expectedPackets = sse_decode_u_32(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_totalPackets = sse_decode_u_32(deserializer);
    var var_filename = sse_decode_opt_String(deserializer);
    var var_fileData = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_errorMsg = sse_decode_opt_String(deserializer);
    var var_sessionId = sse_decode_opt_box_autoadd_u_32(deserializer);
    return DecodeStatus(
      status: var_status,
      percent: var_percent,
      receivedPackets: var_receivedPackets,
      expectedPackets: var_expectedPackets,
      durationMs: var_durationMs,
      totalPackets: var_totalPackets,
      filename: var_filename,
      fileData: var_fileData,
      errorMsg: var_errorMsg,
      sessionId: var_sessionId,
    );
  }

  @protected
  EncodeResult sse_decode_encode_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_gifData = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_totalFrames = sse_decode_u_32(deserializer);
    var var_minFrames = sse_decode_u_32(deserializer);
    var var_errorMsg = sse_decode_opt_String(deserializer);
    return EncodeResult(
      success: var_success,
      gifData: var_gifData,
      totalFrames: var_totalFrames,
      minFrames: var_minFrames,
      errorMsg: var_errorMsg,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  GifDecodeResult sse_decode_gif_decode_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_filename = sse_decode_opt_String(deserializer);
    var var_fileData = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_framesProcessed = sse_decode_u_32(deserializer);
    var var_qrDetected = sse_decode_u_32(deserializer);
    var var_errorMsg = sse_decode_opt_String(deserializer);
    return GifDecodeResult(
      success: var_success,
      filename: var_filename,
      fileData: var_fileData,
      framesProcessed: var_framesProcessed,
      qrDetected: var_qrDetected,
      errorMsg: var_errorMsg,
    );
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_chunked_encode_result(
    ChunkedEncodeResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.zipData, serializer);
    sse_encode_list_list_prim_u_8_strict(self.chunkGifs, serializer);
    sse_encode_list_prim_u_32_strict(self.chunkFrameCounts, serializer);
    sse_encode_list_prim_u_32_strict(self.chunkMinFrames, serializer);
    sse_encode_u_32(self.totalChunks, serializer);
    sse_encode_u_32(self.totalFrames, serializer);
    sse_encode_u_32(self.minFrames, serializer);
    sse_encode_opt_String(self.errorMsg, serializer);
  }

  @protected
  void sse_encode_decode_status(DecodeStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.status, serializer);
    sse_encode_f_32(self.percent, serializer);
    sse_encode_u_32(self.receivedPackets, serializer);
    sse_encode_u_32(self.expectedPackets, serializer);
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_u_32(self.totalPackets, serializer);
    sse_encode_opt_String(self.filename, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.fileData, serializer);
    sse_encode_opt_String(self.errorMsg, serializer);
    sse_encode_opt_box_autoadd_u_32(self.sessionId, serializer);
  }

  @protected
  void sse_encode_encode_result(EncodeResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.gifData, serializer);
    sse_encode_u_32(self.totalFrames, serializer);
    sse_encode_u_32(self.minFrames, serializer);
    sse_encode_opt_String(self.errorMsg, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_gif_decode_result(
    GifDecodeResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.filename, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.fileData, serializer);
    sse_encode_u_32(self.framesProcessed, serializer);
    sse_encode_u_32(self.qrDetected, serializer);
    sse_encode_opt_String(self.errorMsg, serializer);
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
