// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_streaming_packet`, `decode_gif_internal`, `prepare_payload`, `render_qr_1bit`, `render_streaming_qr`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EncodeProgress`, `StreamingPacketHeader`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<void> resetDecoder() =>
    RustLib.instance.api.crateApiSimpleResetDecoder();

Future<DecodeStatus> processChunk({required List<int> data}) =>
    RustLib.instance.api.crateApiSimpleProcessChunk(data: data);

Future<EncodeResult> encodeToGif({
  required String filename,
  required List<int> data,
  required int fps,
  required String eccLevel,
  required int packetSize,
  required double raptorqOverhead,
  required bool compress,
}) => RustLib.instance.api.crateApiSimpleEncodeToGif(
  filename: filename,
  data: data,
  fps: fps,
  eccLevel: eccLevel,
  packetSize: packetSize,
  raptorqOverhead: raptorqOverhead,
  compress: compress,
);

Future<ChunkedEncodeResult> encodeChunkedToZip({
  required String filename,
  required List<int> data,
  required int chunkSizeKb,
  required int fps,
  required String eccLevel,
  required int packetSize,
  required double raptorqOverhead,
  required bool compress,
}) => RustLib.instance.api.crateApiSimpleEncodeChunkedToZip(
  filename: filename,
  data: data,
  chunkSizeKb: chunkSizeKb,
  fps: fps,
  eccLevel: eccLevel,
  packetSize: packetSize,
  raptorqOverhead: raptorqOverhead,
  compress: compress,
);

Future<GifDecodeResult> decodeGifFile({required List<int> gifData}) =>
    RustLib.instance.api.crateApiSimpleDecodeGifFile(gifData: gifData);

Future<GifDecodeResult> decodeZipFile({required List<int> zipData}) =>
    RustLib.instance.api.crateApiSimpleDecodeZipFile(zipData: zipData);

class ChunkedEncodeResult {
  final bool success;
  final Uint8List? zipData;
  final List<Uint8List> chunkGifs;
  final Uint32List chunkFrameCounts;
  final Uint32List chunkMinFrames;
  final int totalChunks;
  final int totalFrames;
  final int minFrames;
  final String? errorMsg;

  const ChunkedEncodeResult({
    required this.success,
    this.zipData,
    required this.chunkGifs,
    required this.chunkFrameCounts,
    required this.chunkMinFrames,
    required this.totalChunks,
    required this.totalFrames,
    required this.minFrames,
    this.errorMsg,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      zipData.hashCode ^
      chunkGifs.hashCode ^
      chunkFrameCounts.hashCode ^
      chunkMinFrames.hashCode ^
      totalChunks.hashCode ^
      totalFrames.hashCode ^
      minFrames.hashCode ^
      errorMsg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChunkedEncodeResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          zipData == other.zipData &&
          chunkGifs == other.chunkGifs &&
          chunkFrameCounts == other.chunkFrameCounts &&
          chunkMinFrames == other.chunkMinFrames &&
          totalChunks == other.totalChunks &&
          totalFrames == other.totalFrames &&
          minFrames == other.minFrames &&
          errorMsg == other.errorMsg;
}

class DecodeStatus {
  final String status;
  final double percent;
  final int receivedPackets;
  final int expectedPackets;
  final BigInt durationMs;
  final int totalPackets;
  final String? filename;
  final Uint8List? fileData;
  final String? errorMsg;
  final int? sessionId;

  const DecodeStatus({
    required this.status,
    required this.percent,
    required this.receivedPackets,
    required this.expectedPackets,
    required this.durationMs,
    required this.totalPackets,
    this.filename,
    this.fileData,
    this.errorMsg,
    this.sessionId,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      percent.hashCode ^
      receivedPackets.hashCode ^
      expectedPackets.hashCode ^
      durationMs.hashCode ^
      totalPackets.hashCode ^
      filename.hashCode ^
      fileData.hashCode ^
      errorMsg.hashCode ^
      sessionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodeStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          percent == other.percent &&
          receivedPackets == other.receivedPackets &&
          expectedPackets == other.expectedPackets &&
          durationMs == other.durationMs &&
          totalPackets == other.totalPackets &&
          filename == other.filename &&
          fileData == other.fileData &&
          errorMsg == other.errorMsg &&
          sessionId == other.sessionId;
}

class EncodeResult {
  final bool success;
  final Uint8List? gifData;
  final int totalFrames;
  final int minFrames;
  final String? errorMsg;

  const EncodeResult({
    required this.success,
    this.gifData,
    required this.totalFrames,
    required this.minFrames,
    this.errorMsg,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      gifData.hashCode ^
      totalFrames.hashCode ^
      minFrames.hashCode ^
      errorMsg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncodeResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          gifData == other.gifData &&
          totalFrames == other.totalFrames &&
          minFrames == other.minFrames &&
          errorMsg == other.errorMsg;
}

class GifDecodeResult {
  final bool success;
  final String? filename;
  final Uint8List? fileData;
  final int framesProcessed;
  final int qrDetected;
  final String? errorMsg;

  const GifDecodeResult({
    required this.success,
    this.filename,
    this.fileData,
    required this.framesProcessed,
    required this.qrDetected,
    this.errorMsg,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      filename.hashCode ^
      fileData.hashCode ^
      framesProcessed.hashCode ^
      qrDetected.hashCode ^
      errorMsg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GifDecodeResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          filename == other.filename &&
          fileData == other.fileData &&
          framesProcessed == other.framesProcessed &&
          qrDetected == other.qrDetected &&
          errorMsg == other.errorMsg;
}
